# Generated by Django 3.2.25 on 2024-06-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriedetail',
            name='owner',
            field=models.ForeignKey(blank=True, default=1717854740, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='owner',
            field=models.ForeignKey(blank=True, default=1717854740, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
